### ISSUE TITLE
Progress on "Symbol and Rom Method" and "Minimal Recomp Example" mentioned a while ago

### ISSUE THREAD

**Issue by SirDiabo** [N64Recomp/N64Recomp#105]
A while ago, wiseguy mentioned that to help with the elf file thing that everyone is getting stuck on, he could make a minimal recomp example project or add other ways of getting this to work, like providing a symbol list instead of an elf file. Any news?
Also, I read something about it maybe being possible to write a tool that takes a ROM file and spits out an elf file that would include all necessary data. If someone were to make this tool, where would they put it? And how would they let us know?

**Comment by SirDiabo** [comment]
Another thing, I saw a lot of people interested in using this tool to get their favorite games on pc.
On that mystical ninja discord server in the recomp channel, multiple Reddit threads, lots of issue threads over here and at the zelda64 repo.
Would a discord server for this make sense?
To have a place where people who are interested in updates about this tool or Zelda64 or other people's recomp projects can accumulate and help each other and help with providing documentation and share their interest in bringing n64 games to modern hardware.

**Comment by Mr-Wiseguy** [comment]
> minimal recomp example project

When I have something put together for that, I'll post it on the existing issue where I mentioned it and in the readme of this repo. Please keep discussion about it in the existing issue. Unfortunately my free time has been very limited recently, and the time I do have is mostly spent working on recomp mod support for future releases as well as helping with other recomps that are being worked on currently.

> symbol list instead of an elf file

That feature is already implemented, I just forgot to update the part in the readme about it. You can see an example here: https://github.com/Zelda64Recomp/Zelda64RecompSyms

> Also, I read something about it maybe being possible to write a tool that takes a ROM file and spits out an elf file that would include all necessary data

I've never heard of anyone saying anything about this, and I can guarantee you there's no way it can be done automatically. Creating an elf file or symbol file for a given ROM is an involved process that requires some complex reverse engineering on a per-ROM basis in order to create a disassembly of the ROM, similar to the process of starting a decomp. You need to find all the code in a given ROM, which includes figuring out any compression algorithm that may be used if there's compressed code in the ROM, and then you have to figure out how that code gets loaded at runtime. You also need to split the code up into individual functions.

This process doesn't necessarily take a long time (it can be done in the span of days for somebody who has experience with it), but that doesn't mean it's simple. A lot of this can be done with reverse engineering tools like [splat](https://github.com/ethteck/splat), but teaching people how to use splat and how to reverse engineer N64 ROMs is outside the scope of what I'd cover in an example project. The example project would serve as a guide on how to take a ROM with an existing disassembly/decompilation and use it as the basis for a recompilation.

There's also the fact that getting a ROM running doesn't mean it's ready to be released. There's polish required for a high quality release beyond just getting it running, which can vary in complexity from ROM to ROM. Things like fixes for game bugs that only show up when running so quickly, widescreen support, improvements to the high framerate experience, updated controls, etc.

> Would a discord server for this make sense?

A discord server would be cool, but I'm not interested in moderating one and I don't know people who I trust that would be willing to do so in my stead.
