### ISSUE TITLE
Generating symbol toml

### ISSUE THREAD

**Issue by arefdsg** [N64Recomp/N64Recomp#81]
How do you generate the symbol toml like in MM?

**Comment by Mr-Wiseguy** [comment]
Right now it's not exposed from command line since I haven't gotten around to argument parsing, but you set [this boolean](https://github.com/N64Recomp/N64Recomp/blob/ba4aede49c9a5302ecfc1fa599f7acc3925042f9/src/main.cpp#L1492) to true. From there, you give the tool a toml that points at an elf file (usually from a decompilation) like [the one zelda recomp used to use](https://github.com/Zelda64Recomp/Zelda64Recomp/blob/d5fb5f50c122cc366e04713698b19e876a1fb6b0/us.rev1.toml).

It'll generate a function symbol toml and a data symbol toml, like you can find [here](https://github.com/Zelda64Recomp/Zelda64RecompSyms) for zelda recomp.
